# Generated by Django 6.0 on 2026-02-01 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_alter_producerprofile_category_and_more'),
        ('products', '0003_create_initial_categories'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_905dc3_idx',
            old_name='products_pr_category_created_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='availability_end_month',
            field=models.IntegerField(blank=True, choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], null=True, verbose_name='Mois de fin'),
        ),
        migrations.AddField(
            model_name='product',
            name='availability_start_month',
            field=models.IntegerField(blank=True, choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], null=True, verbose_name='Mois de début'),
        ),
        migrations.AddField(
            model_name='product',
            name='availability_type',
            field=models.CharField(choices=[('all_year', "Tout l'année"), ('custom', 'Période personnalisée')], default='all_year', max_length=20, verbose_name='Type de disponibilité'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nom du produit'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['producer', 'created_at'], name='products_pr_produce_2ef5d1_idx'),
        ),
    ]
