# Generated by Django 5.0.1 on 2025-12-01 21:42

import apps.producers.validators
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="producerprofile",
            name="email_contact",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email de contact"),
        ),
        migrations.AddField(
            model_name="producerprofile",
            name="opening_hours",
            field=models.TextField(blank=True, max_length=500, verbose_name="Horaires d'ouverture"),
        ),
        migrations.AddField(
            model_name="producerprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Téléphone"),
        ),
        migrations.AddField(
            model_name="producerprofile",
            name="website",
            field=models.URLField(blank=True, verbose_name="Site web"),
        ),
        migrations.AlterField(
            model_name="producerphoto",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="producerphoto",
            name="image_file",
            field=models.ImageField(
                upload_to="producers/%Y/%m/%d/",
                validators=[apps.producers.validators.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="producerprofile",
            name="category",
            field=models.CharField(
                choices=[
                    ("maraîcher", "Maraîcher"),
                    ("éleveur", "Éleveur"),
                    ("apiculteur", "Apiculteur"),
                    ("arboriculteur", "Arboriculteur"),
                    ("céréalier", "Céréalier"),
                    ("autre", "Autre"),
                ],
                db_index=True,
                default="autre",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="producerprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="producerprofile",
            name="description",
            field=models.TextField(blank=True, max_length=2000, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="producerprofile",
            name="latitude",
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="producerprofile",
            name="longitude",
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="producerprofile",
            name="name",
            field=models.CharField(
                max_length=200,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="Nom de l'exploitation",
            ),
        ),
        migrations.AddIndex(
            model_name="producerphoto",
            index=models.Index(
                fields=["producer", "created_at"], name="producers_p_produce_9a8631_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="producerprofile",
            index=models.Index(
                fields=["category", "created_at"], name="producers_p_categor_354342_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="producerprofile",
            index=models.Index(
                fields=["latitude", "longitude"], name="producers_p_latitud_fa7e6f_idx"
            ),
        ),
    ]
