# Generated by Django 6.0 on 2026-02-01 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_producerprofile_email_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerprofile',
            name='category',
            field=models.CharField(choices=[('maraîchage', 'Maraîchage'), ('élevage', 'Élevage'), ('apiculture', 'Apiculture'), ('arboriculture', 'Arboriculture'), ('céréaliculture', 'Céréaliculture'), ('pêche', 'Pêche'), ('brasserie', 'Brasserie'), ('distillerie', 'Distillerie'), ('fromagerie', 'Fromagerie'), ('boulangerie', 'Boulangerie'), ('viticulture', 'Viticulture'), ('charcuterie', 'Charcuterie'), ('autre', 'Autre')], db_index=True, default='autre', max_length=50),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=7, max_digits=11),
        ),
        migrations.CreateModel(
            name='SaleMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_type', models.CharField(choices=[('on_site', 'Vente sur place / point de vente'), ('phone_order', 'Commande par téléphone'), ('vending_machine', 'Distributeur automatique'), ('delivery', 'Livraison'), ('market', 'Marchés')], max_length=50, verbose_name='Type de mode de vente')),
                ('title', models.CharField(help_text="Ex: 'Vente à la ferme', 'Marché de Savenay'", max_length=200, verbose_name='Titre')),
                ('instructions', models.TextField(help_text="Ex: 'Merci d'appeler 1 jour à l'avance', 'Apportez vos contenants'", max_length=500, verbose_name='Consigne obligatoire')),
                ('phone_number', models.CharField(blank=True, help_text="Obligatoire pour 'Commande par téléphone'", max_length=20, verbose_name='Numéro de téléphone')),
                ('website_url', models.URLField(blank=True, help_text='Pour commandes en ligne (livraison)', verbose_name='Site web')),
                ('is_24_7', models.BooleanField(default=False, help_text='Pour distributeur automatique', verbose_name='Disponible 24/7')),
                ('location_address', models.CharField(blank=True, help_text="Si différente de l'adresse principale", max_length=500, verbose_name='Adresse du point de vente')),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude du point de vente')),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True, verbose_name='Longitude du point de vente')),
                ('market_info', models.TextField(blank=True, help_text='Jours, horaires et lieux des marchés', max_length=1000, verbose_name='Indications marché')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_modes', to='producers.producerprofile')),
            ],
            options={
                'verbose_name': 'Mode de vente',
                'verbose_name_plural': 'Modes de vente',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='Jour de la semaine')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Fermé ce jour')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name="Heure d'ouverture")),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fermeture')),
                ('sale_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='producers.salemode')),
            ],
            options={
                'verbose_name': "Horaire d'ouverture",
                'verbose_name_plural': "Horaires d'ouverture",
                'ordering': ['day_of_week'],
            },
        ),
        migrations.AddIndex(
            model_name='salemode',
            index=models.Index(fields=['producer', 'order'], name='producers_s_produce_5671d0_idx'),
        ),
        migrations.AddIndex(
            model_name='openinghours',
            index=models.Index(fields=['sale_mode', 'day_of_week'], name='producers_o_sale_mo_237197_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='openinghours',
            unique_together={('sale_mode', 'day_of_week')},
        ),
    ]
